// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Infrastructure.DataContext;

#nullable disable

namespace Sample.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sample.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("Mã số");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian khởi tạo");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasComment("Id người tạo");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian xóa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("Tên gọi");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian chỉnh sửa cuối");

                    b.Property<Guid?>("UpdatorId")
                        .HasColumnType("char(36)")
                        .HasComment("Id người chỉnh sửa");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreateAt");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DeleteAt");

                    b.HasIndex("Name");

                    b.HasIndex("UpdateAt");

                    b.HasIndex("UpdatorId");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("653dc4d4-ca05-45ac-83cd-e98fa91b890f"),
                            Code = "root",
                            Name = "Root"
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Mã");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian khởi tạo");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasComment("Id người tạo");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian xóa");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasComment("Mô tả");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("Thời gian chỉnh sửa cuối");

                    b.Property<Guid?>("UpdatorId")
                        .HasColumnType("char(36)")
                        .HasComment("Id người chỉnh sửa");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasComment("Giá trị");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreateAt");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DeleteAt");

                    b.HasIndex("UpdateAt");

                    b.HasIndex("UpdatorId");

                    b.ToTable("Setting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ccd8c5-6656-48f5-a73e-8d75895c9adc"),
                            Code = "SessionLifetime",
                            Description = "Thời gian sống của session (phút)",
                            Value = "240"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
