// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Infrastructure.Persistences;

#nullable disable

namespace Sample.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220816054357_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sample.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<string>("AvatarLink")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("PermissionGroupId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevel");

                    b.HasIndex("Code");

                    b.HasIndex("CreateDateTime");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("PermissionGroupId");

                    b.HasIndex("UpdateDateTime");

                    b.HasIndex("UpdatorId");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("653dc4d4-ca05-45ac-83cd-e98fa91b890f"),
                            AccessLevel = 0,
                            IsDeleted = true,
                            Name = "Root"
                        },
                        new
                        {
                            Id = new Guid("b81d0c90-3b91-44d4-bb00-95a5925fa5c6"),
                            AccessLevel = 1,
                            IsDeleted = false,
                            Name = "Admin",
                            PermissionGroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77")
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.AccountAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HashPasswordKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HashedPassword")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Code");

                    b.HasIndex("CreateDateTime");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UpdateDateTime");

                    b.HasIndex("UpdatorId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AccountAuth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("653dc4d4-ca05-45ac-83cd-e98fa91b890f"),
                            AccountId = new Guid("653dc4d4-ca05-45ac-83cd-e98fa91b890f"),
                            HashPasswordKey = "8sBXJjPl1BaK1ppd0PNMB366NHhmAx",
                            HashedPassword = "F0DC6BFBD368CDD9D63FC264C8B76E9F",
                            IsDeleted = false,
                            Username = "root"
                        },
                        new
                        {
                            Id = new Guid("b81d0c90-3b91-44d4-bb00-95a5925fa5c6"),
                            AccountId = new Guid("b81d0c90-3b91-44d4-bb00-95a5925fa5c6"),
                            HashPasswordKey = "xE8czZlAixQOJDQ0oR7PqlYJUcywj6",
                            HashedPassword = "73906ACDE3F2288B37120E99886A57D7",
                            IsDeleted = false,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.AccountSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiryDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Code");

                    b.HasIndex("CreateDateTime");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ExpiryDatetime");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UpdateDateTime");

                    b.HasIndex("UpdatorId");

                    b.ToTable("AccountSession");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Code");

                    b.HasIndex("CategoryName");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Code = "profile.update",
                            CategoryName = "Thông tin cá nhân",
                            Name = "Sửa thông tin cá nhân"
                        },
                        new
                        {
                            Code = "account.create",
                            CategoryName = "Tài khoản",
                            Name = "Tạo tài khoản"
                        },
                        new
                        {
                            Code = "account.read",
                            CategoryName = "Tài khoản",
                            Name = "Đọc tài khoản"
                        },
                        new
                        {
                            Code = "account.update",
                            CategoryName = "Tài khoản",
                            Name = "Sửa tài khoản"
                        },
                        new
                        {
                            Code = "account.delete",
                            CategoryName = "Tài khoản",
                            Name = "Xóa tài khoản"
                        },
                        new
                        {
                            Code = "account.changelog",
                            CategoryName = "Tài khoản",
                            Name = "Xem log tài khoản"
                        },
                        new
                        {
                            Code = "account.export",
                            CategoryName = "Tài khoản",
                            Name = "Xuất tài khoản"
                        },
                        new
                        {
                            Code = "permission.create",
                            CategoryName = "Quyền",
                            Name = "Tạo quyền"
                        },
                        new
                        {
                            Code = "permission.read",
                            CategoryName = "Quyền",
                            Name = "Đọc quyền"
                        },
                        new
                        {
                            Code = "permission.update",
                            CategoryName = "Quyền",
                            Name = "Sửa quyền"
                        },
                        new
                        {
                            Code = "permission.delete",
                            CategoryName = "Quyền",
                            Name = "Xóa quyền"
                        },
                        new
                        {
                            Code = "permission.changelog",
                            CategoryName = "Quyền",
                            Name = "Xem log quyền"
                        },
                        new
                        {
                            Code = "permission.export",
                            CategoryName = "Quyền",
                            Name = "Xuất quyền"
                        },
                        new
                        {
                            Code = "setting.read",
                            CategoryName = "Thiết lập",
                            Name = "Đọc thiết lập"
                        },
                        new
                        {
                            Code = "setting.update",
                            CategoryName = "Thiết lập",
                            Name = "Sửa thiết lập"
                        },
                        new
                        {
                            Code = "setting.changelog",
                            CategoryName = "Thiết lập",
                            Name = "Xem log thiết lập"
                        },
                        new
                        {
                            Code = "setting.export",
                            CategoryName = "Thiết lập",
                            Name = "Xuất thiết lập"
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreateDateTime");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("UpdateDateTime");

                    b.HasIndex("UpdatorId");

                    b.ToTable("PermissionGroup");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            Code = "Admin",
                            HierarchyLevel = 0,
                            IsDeleted = false,
                            Name = "Nhóm quyền quản trị"
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.PermissionValue", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("ActualValue")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Code", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("PermissionValue");

                    b.HasData(
                        new
                        {
                            Code = "profile.update",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "account.create",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "account.read",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "account.update",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "account.delete",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "account.changelog",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "account.export",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "permission.create",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "permission.read",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "permission.update",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "permission.delete",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "permission.changelog",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "permission.export",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "setting.read",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "setting.update",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "setting.changelog",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        },
                        new
                        {
                            Code = "setting.export",
                            GroupId = new Guid("41097c99-a6c7-4056-9ef5-be1de1fdfe77"),
                            ActualValue = true,
                            Value = 1
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreateDateTime");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UpdateDateTime");

                    b.HasIndex("UpdatorId");

                    b.ToTable("Setting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ccd8c5-6656-48f5-a73e-8d75895c9adc"),
                            Code = "AccountRegisterAutoAccept",
                            Description = "Tự động duyệt các tài khoản mới đăng ký",
                            IsDeleted = false,
                            Value = "false"
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.Account", b =>
                {
                    b.HasOne("Sample.Domain.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("Accounts")
                        .HasForeignKey("PermissionGroupId");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Sample.Domain.Entities.AccountAuth", b =>
                {
                    b.HasOne("Sample.Domain.Entities.Account", "Account")
                        .WithMany("Auths")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Sample.Domain.Entities.AccountSession", b =>
                {
                    b.HasOne("Sample.Domain.Entities.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Sample.Domain.Entities.PermissionGroup", b =>
                {
                    b.HasOne("Sample.Domain.Entities.PermissionGroup", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Sample.Domain.Entities.PermissionValue", b =>
                {
                    b.HasOne("Sample.Domain.Entities.Permission", "Permission")
                        .WithMany("PermissionValues")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sample.Domain.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("PermissionValues")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Account", b =>
                {
                    b.Navigation("Auths");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Permission", b =>
                {
                    b.Navigation("PermissionValues");
                });

            modelBuilder.Entity("Sample.Domain.Entities.PermissionGroup", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Childs");

                    b.Navigation("PermissionValues");
                });
#pragma warning restore 612, 618
        }
    }
}
