// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sample.Data.DataContexts;

namespace Sample.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Sample.Data.Entities.SettingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreateDatetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("UpdateDatetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_datetime");

                    b.Property<Guid?>("UpdaterId")
                        .HasColumnType("uuid")
                        .HasColumnName("updater_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_setting");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_setting_code");

                    b.HasIndex("CreateDatetime")
                        .HasDatabaseName("ix_setting_create_datetime");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_setting_creator_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_setting_is_deleted");

                    b.HasIndex("UpdateDatetime")
                        .HasDatabaseName("ix_setting_update_datetime");

                    b.HasIndex("UpdaterId")
                        .HasDatabaseName("ix_setting_updater_id");

                    b.ToTable("setting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26e84c09-8aa7-4e90-b1f6-f6e2ff6ef14c"),
                            Code = "a",
                            Description = "description",
                            IsDeleted = false,
                            Value = "value"
                        },
                        new
                        {
                            Id = new Guid("cce3e3d7-f893-4a0d-bff9-d63cdfe8abe5"),
                            Code = "b",
                            Description = "description",
                            IsDeleted = false,
                            Value = "value"
                        });
                });

            modelBuilder.Entity("TripleSix.Core.AutoAdmin.ObjectLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("after_data");

                    b.Property<string>("BeforeData")
                        .HasColumnType("text")
                        .HasColumnName("before_data");

                    b.Property<DateTime?>("Datetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datetime");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_type");

                    b.HasKey("Id")
                        .HasName("pk_object_log");

                    b.ToTable("object_log");
                });
#pragma warning restore 612, 618
        }
    }
}
