name: Publish Nuget

on:
    push:
        branches:
        - master
    pull_request:
        types:
        - closed
        branches:
        - master

env:
    PACK_PROJECT: Core
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Setup .NET
          uses: actions/setup-dotnet@v1

        - name: Pack NuGet package
          run: dotnet pack ${{ env.PACK_PROJECT }} --configuration Release --output out
            
    deploy:
        runs-on: ubuntu-latest
        needs:
        - build
        steps:
        - name: Publish NuGet package
          run: dotnet nuget push ./<project>/out/*.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
