name: Publish Nuget

on:
    push:
        branches:
        - master

env:
    PACK_PROJECT: Core
    
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Setup .NET
          uses: actions/setup-dotnet@v1

        - name: Pack NuGet package
          run: dotnet pack ${{ env.PACK_PROJECT }} --configuration Release --output dist

        - name: Publish NuGet package
          run: dotnet nuget push ./dist/*.nupkg --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
